_wandb:
    value:
        cli_version: 0.23.1
        e:
            il14yxw4t9lvyuft8hxckbkrwac8x32o:
                codePath: run3.ipynb
                codePathLocal: run3.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "499963174912"
                        used: "415057948672"
                email: malcolm_grant@brown.edu
                executable: /Users/Mac/Desktop/csci1470/final-run3/run3_env/bin/python
                git:
                    commit: 2e988035a30cbd98cfba09415587fd396d39b9ae
                    remote: https://github.com/MalcolmCS15/Run-3-Agent.git
                host: Malcolms-MacBook-Pro-51.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-x86_64-i386-64bit
                program: run3.ipynb
                python: CPython 3.11.13
                root: /Users/Mac/Desktop/csci1470/final-run3
                startedAt: "2025-12-08T20:57:35.972348Z"
                writerId: il14yxw4t9lvyuft8hxckbkrwac8x32o
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 2
                - 3
            "2":
                - 2
                - 3
            "3":
                - 2
                - 16
            "4": 3.11.13
            "5": 0.23.1
            "8":
                - 1
            "12": 0.23.1
            "13": darwin-x86_64
architecture:
    value: CNN
clip_ratio:
    value: 0.1
entropy_coef:
    value: 0.02
eval_episodes:
    value: 10
frame_stack:
    value: 4
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
max_grad_norm:
    value: 0.5
mini_batch_size:
    value: 32
num_actions:
    value: 16
num_parameters:
    value: 4863857
resolution:
    value: 128
runway_h:
    value: 120
runway_reward:
    value: 1
runway_w:
    value: 60
runway_x:
    value: 600
runway_y:
    value: 480
steps_per_epoch:
    value: 512
train_epochs:
    value: 15
update_epochs:
    value: 4
value_coef:
    value: 0.5
